name: '${name}'
version: '${version}'
main: '${main}'
softdepend:
  - Lands

commands:
  fly:
    description: Command to toggle fly
    permission: flyingallowed.command.fly
    aliases:
      - flight
      - flymode
  set-fly:
    description: Command to set fly
    permission: flyingallowed.command.set-fly
    aliases:
      - setfly
      - setflight
      - set-flight
      - setflymode
      - sfly
  fly-bypass:
    description: Command to bypass flight checks
    permission: flyingallowed.command.fly-bypass
    aliases:
      - fb
      - flybypass
      - flyb
      - flightbypass